augmentation_level: none
backbone: resnet18
batch_size: 50
data_path: /home/gregor/Desktop/segnet/comma10k
epochs: 3
eps: 1.0e-07
height: 218
lr: 0.001
num_workers: 6
resume_from_checkpoint: null
seed_from_checkpoint: null
version: rapidTest
weight_decay: 1.0e-06
width: 291
